# Generated by Django 3.1.3 on 2020-11-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoldGoods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
